### ISSUE TITLE
SHOULD semantically version project artifacts . You MUST tag all versions in GitHub with the exact version name. E.g.: 0.1.0.

### ISSUE THREAD

**Issue by rgritti** [zalando-stups/skrop#58]
# Actual Status
There is no publishing concept in this project yet. We need to onboard one, applying that rule of using semantic versioning, GitHub versions and GIT tags.

# Tasks
- [x] Document how to manually publish this project to Zalando Open-Source Docker Registry (including the manual GIT-Tag and GH-Version)
- [x] Configure _Travis CI_ to perform that release task (check with _Arpad_ how they do it)
  - Should it try to continuous-deliver at each merge to `master`?
  - If so, how to automatically "decide" which digit of the semantic version to increment?
- [x] Document how to manage versions (the _ideal_ version of it, on top of the _manual_ version already documented).

**Comment by Adeynack** [comment]
# Travis and versions

Get inspiration from _Skipper_, task `ci-trigger` in their `Makefile`.

**Comment by Adeynack** [comment]
Last try [here](https://travis-ci.org/zalando-stups/skrop/builds/319261415)
Failed to GIT TAG the version. Check Travis log for error detail (near the end).

**Comment by Adeynack** [comment]
@danpersa @rgritti and other maintainers: I will leave it to you to re-scope this issue and close it if you will.

The current status is a milestone in itself. Now, _Travis CI_ is bumping up automatically the _patch version_. See the README under section [Versioning](https://github.com/zalando-stups/skrop/#versioning) for details. It was unfortunately not possible in the time I had to work on this to find a more interesting solution. However, this actual solution, even if a bit manual, is an upgrade to not having automatic versioning at all.

Have a great continuation on this project!
